### ISSUE TITLE
Android Collapsing Toolbars on Main Page

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/nativescript-marketplace-demo#1]
Implement collapsible header and action bar on the main page:
[Collapsing Toolbars](http://android-developers.blogspot.bg/2015/05/android-design-support-library.html).

**Comment by PanayotCankov** [comment]
We have considered this with the designers and it was decided that we don't need collapsible header at the moment.

**Comment by MuhammadTahir92** [comment]
now its 2018 so please concern again if some thing is changed
