### ISSUE TITLE
ListView: Selection - Both buttons (like, delete) are visible when swipe an item to the edge

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-marketplace-demo#101]
![screenshot_20160122-171249](https://cloud.githubusercontent.com/assets/5803037/12514593/c8aa682c-c12c-11e5-85f7-c67836e39f0e.png)

**Comment by PixelPartner** [comment]
I could not reproduce it, but in the simple ToDo listview sample in my very first App interaction, I managed to make both left and right swipe action buttons completely disappear. Not for all, but for one.
