### ISSUE TITLE
ListView: Recipes scrolls very jaggy - doesn't feel native at all

### ISSUE THREAD

**Issue by PixelPartner** [NativeScript/nativescript-marketplace-demo#102]
On iOS it seems to me, that the overall smoothly accellerated scolling is interupted by dynamically adding entries that show up next. How about adding a time base to hide this by deliberately skipping frames.

**Comment by PanayotCankov** [comment]
There are several issues that slow the performance there. We have focused our development efforts in solving all these problems to hit 60fps in the list view example. It should be delivered for v2.1.

Thank you for your feedback,

**Comment by dtopuzov** [comment]
Performance should be better now.
