### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-marketplace-demo#104]
branch: master

![screenshot_2016-02-23-14-01-14](https://cloud.githubusercontent.com/assets/5803037/13251145/1eddcf54-da37-11e5-95b7-c8092b76f8a1.png)

**Comment by PanayotCankov** [comment]
Master works with master build from the modules, runtimes, CLI, nativescript-telerik-ui, fresco etc. It is nearly impossible to rebuild everything by hand at your side and re-run it.

Now when we have 1.6.0 officially released we will probably merge everything from the master branch into the **production** and make it work with the official versions.

Stay tuned.

**Comment by PanayotCankov** [comment]
You need to install the master branch of the runtimes, cli, modules, widgets and telerik-ui from our Jenkins builds.

It looks like you are missing the widgets.
