### ISSUE TITLE
Pulled latest and app fails on compiling.

### ISSUE THREAD

**Issue by lelong37** [NativeScript/nativescript-marketplace-demo#105]
Pulled latest from Production branch

- npm install
- tns build android - failed
- tns build ios

![image](https://cloud.githubusercontent.com/assets/4691404/13285492/816cb188-dac0-11e5-93f5-f0abe508208b.png)

**Comment by milen-3web** [comment]
Same here, guys.

**Comment by PanayotCankov** [comment]
Hi everyone,

We have just merged the latest changes from our master to our production branch.
The master works with internal builds of the modules, nativescript-telerik-ui, etc. and is not quite friendly to the public.
The production is intended to be used from outside developers and be working fine with the officially released and published npm packages.
Could you now try to checkout and pull the production branch and try to build the demo?
If it still crashes could you paste here a little bit more extensive log. I mean the 10 lines above the "BUILD FAILED", so we can have a better understanding of what is happening? I would expect something like:

```
:config phase:  createDefaultIncludeFiles
	+found plugins: fresco
	+found plugins: nativescript-telerik-analytics
	+creating include.gradle file for: /Users/cankov/GitRoot/NativeScript/nativescript-marketplace-demo/platforms/android/configurations/nativescript-telerik-analytics
	+found plugins: nativescript-telerik-ui

:config phase:  createPluginsConfigFile
	+creating product flavors include.gradle file in configurations folder...

FAILURE: Build failed with an exception.

* Where:
Script '/Users/cankov/GitRoot/NativeScript/nativescript-marketplace-demo/app/App_Resources/Android/app.gradle' line: 4

* What went wrong:
A problem occurred evaluating script.
> No such property: generatedDensities for class: com.android.build.gradle.internal.dsl.ProductFlavor_Decorated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.022 secs
```
