### ISSUE TITLE
Item layouts example crashes when tap the button for linear layout

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-marketplace-demo#110]
Go to ListView's example - Item layouts. Click on the button for linear layout.

![screenshot_20160229-184126](https://cloud.githubusercontent.com/assets/5803037/13401749/131b248a-df16-11e5-920f-9c6700e58244.png)

**Comment by dtopuzov** [comment]
Fixed in latest versions.
