### ISSUE TITLE
Item layouts example crashes when long press (hold) an item

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-marketplace-demo#113]
Long press (hold) an item for 2-3sec and don't to move it. 

![screenshot_20160229-184528](https://cloud.githubusercontent.com/assets/5803037/13402361/8deb5ae8-df18-11e5-862d-963c77d1c4c6.png)

**Comment by dtopuzov** [comment]
Fixed with latest versions.
