### ISSUE TITLE
Item's content disappers in Selection example (ListView)

### ISSUE THREAD

**Issue by Natalia-Hristova** [NativeScript/nativescript-marketplace-demo#114]
1. Go to ListView's Selection example.
2. Go to "Favorites".
3. Slide from right to left to see the "Delete button".
4. Tap under the items.

![screenshot_20160229-191412](https://cloud.githubusercontent.com/assets/5803037/13402727/46f38f1e-df1a-11e5-9d58-0e356f99c650.png)

**Comment by dtopuzov** [comment]
Sometime (in rare cases) I'm able to reproduce the same end result when tap and hold and then swipe fast from right to left.

**Comment by Plamen5kov** [comment]
One more way to reproduce this issue:
1. Go to ListView's Selection example.
2. Go to "Favorites".
3. Go to "All".
4. Slide first element right (heart apears)
5. Tap on the heart.
