### ISSUE TITLE
App Store version of the app?

### ISSUE THREAD

**Issue by aaweb** [NativeScript/nativescript-marketplace-demo#197]
Hey there

I saw the app has been updated on iOS in the App Store to version 2 and it looks stunning. However, the code in this repo seems to be different. Where could I find the latest samples?

Cheers,
Andy

**Comment by tjvantoll** [comment]
Hey @aaweb,

Sorry for the late reply. The code is actually in the master branch at https://github.com/NativeScript/nativescript-marketplace-demo/tree/master.

**Comment by PanayotCankov** [comment]
We will merge the master in pruduction soon.
The reason we haven't done it is the master works with pre-release versions of telerik-ui and the modules.

**Comment by hamorphis** [comment]
@aaweb The `production` branch now has the new version of the app.
