### ISSUE TITLE
The app crashes on Asus tablet running Api18

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-marketplace-demo#210]
The crash is reproduced while switching the chart samples and Item Layots sample.

App's version under test:
https://github.com/NativeScript/nativescript-marketplace-demo/tree/a4ec2aad507beab437b77126e3062cb52a4fbfe7

Sample repro steps:
- open Pie Series examples and go through them
- open the Items Layouts example and wait for a while
- repeat the steps above

Logs:
https://gist.github.com/vchimev/489f0eccc0ab04556da42b93854ac2a1
https://gist.github.com/vchimev/a72134c957d5064e7d0eb912d0ab6f66
https://gist.github.com/vchimev/967c1330fd791f754aee69832c1ea816

//CC: @tzraikov, @slavchev

**Comment by hamorphis** [comment]
@slavchev is currently investigating the crash log.

**Comment by dtopuzov** [comment]
Fixed in latest versions.
