### ISSUE TITLE
Split screen mode not working

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-marketplace-demo#212]
The app do not work in split screen mode (in Android N). A system message is displayed that the app is not supported.

**Comment by valentinstoychev** [comment]
https://developer.android.com/preview/features/multi-window.html#configuring

**Comment by NickIliev** [comment]
@valentinstoychev  I have tested on real device and the split mode works on my side.
At this very moment the documentation states the following:

> If your app targets API level 24, but you do not specify a value for this attribute, the attribute's value defaults to true

So even if we do not set explicitly `android:resizeableActivity="true"` the default value will be true for API24
