### ISSUE TITLE
install nativescript-market-demo app on android ,but on two phone,show 2 errors

### ISSUE THREAD

**Issue by codeHui** [NativeScript/nativescript-marketplace-demo#223]
I install nativescript-market-demo app on android ,but on two phone,show 2 errors when the app is opened.1:

one is:
com.tns.NativeScriptException: 
Calling js method onTouch failed

TypeError: Cannot set property 'isEnabled' of undefined
File: "/data/data/org.nativescript.examples/files/app/tns_modules/ui/gestures/gestures.js, line: 97, column: 40

the other is:
java.lang.InternalError: Thread starting during runtime shutdown
    at java.lang.Thread.nativeCreate(Native Method)
    at java.lang.Thread.start(Thread.java:1078)
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)

**Comment by codeHui** [comment]
tns-android:2.20;tns-core-module 2.21

**Comment by codeHui** [comment]
tns-android:2.20;tns-core-module 2.2.1

**Comment by dtopuzov** [comment]
@codeHui can you give some more details. Do you try to build if form source or you install it from store.
If you try to build it from core - which branch?
