### ISSUE TITLE
Google Play version is not available to my country

### ISSUE THREAD

**Issue by zertyz** [NativeScript/nativescript-marketplace-demo#224]
As Google Play says when accessing the provided link on the readme https://play.google.com/store/apps/details?id=org.nativescript.nativescriptmarketplacedemo&amp;hl=en

btw, I live in Brazil.

**Comment by dtopuzov** [comment]
App id was cahnges, here it is:
https://play.google.com/store/apps/details?id=org.nativescript.examples

**Comment by realtebo** [comment]
Please, update readme link
