### ISSUE TITLE
Problems building, pod error for IQKeyboardManager

### ISSUE THREAD

**Issue by kritollm** [NativeScript/nativescript-marketplace-demo#230]
I didn't save the error message, but here is the fix if you see some red warning about the IQKeyboardManager.

The solution is from [here](http://stackoverflow.com/a/25169215/3717718):

```
  $ pod repo remove master
  $ pod setup
  $ pod install
```

the pod setup command can take very (very) long time.

**Comment by dtopuzov** [comment]
```pod setup``` is not related with IQKeyboardManager, it is something general you should do when Cocoa Pods are installed.
