### ISSUE TITLE
Share code between components

### ISSUE THREAD

**Issue by shafihuzaib** [NativeScript/nativescript-marketplace-demo#243]
Sharing certain code between components is always necessary. For example, the `get page()` method to access the `Page` object for nativescript.

Actually I want the following code to be available in all the components. Can you please propose a way to do that?

    protected _page: any;

    protected get page() {
        if (Config.PageClass) {
        if (!this._page) {
            this._page = this.injector.get(Config.PageClass);
        }

        return this._page;
        }
    }

**Comment by NickIliev** [comment]
clsoing this due to inactivity

@sebawita please post a how-to related question in the community channels (like [this one](https://discourse.nativescript.org/)) where they would have greater visibility and a greater chance of receiving fast answers.
