### ISSUE TITLE
[Selection Example] Extra empty space after item deletion

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-marketplace-demo#244]
Platform: iOS
Version: nativescript-telerik-ui-pro@1.5.1
Example: https://github.com/NativeScript/nativescript-marketplace-demo/tree/master/app/examples/listview/selection

Steps:
- open Selection example
- delete the first item

Result:
![screen shot 2016-12-05 at 4 15 36 pm](https://cloud.githubusercontent.com/assets/12251337/20888098/1288f8f4-bb06-11e6-8df2-450405150fc5.png)

**Comment by vchimev** [comment]
There is similar problem for Android which is randomly reproducible:

![screen](https://cloud.githubusercontent.com/assets/12251337/21260576/448046fa-c38f-11e6-9ed2-85e21e20c974.png)

**Comment by NickIliev** [comment]
CLosing this issue as it is no longer reproducible with the latest `nativescript-ui-listivew`
