### ISSUE TITLE
The marketplace demo app launches slower with version 2.4

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-marketplace-demo#245]
The marketplace demo application built with {N} 2.4.0 launches for ~3s684ms. For a reference, the same app built with {N} 2.2.0 launches for ~2s968ms. Both times are for the app built with a snapshot of the cross-platform modules.

Device: Nexus 6P
Android: 6.0.1

**Comment by vchimev** [comment]
It seems that the delay is caused by adding the push notifications support (https://github.com/NativeScript/nativescript-marketplace-demo/pull/232).

- the last app built with no push notifications support starts for ~2s684ms. ADB logcat: [2016.11.22.1+2s684ms.txt](https://github.com/NativeScript/nativescript-marketplace-demo/files/649335/2016.11.22.1.2s684ms.txt)
- the first app built with push notifications support starts for ~3s480ms. ADB logcat:
[2016.11.22.2+3s480ms.txt](https://github.com/NativeScript/nativescript-marketplace-demo/files/649340/2016.11.22.2.3s480ms.txt)

**Comment by PanayotCankov** [comment]
Disabling firebase crash reporting speeds things up a lot.
Removing this from the firebase plugin:
 // compile "com.google.firebase:firebase-crash:9.8.+"
Boosts startup time from 3.5 to 2.8 secs.

**Comment by vchimev** [comment]
Thanks, @PanayotCankov!
