### ISSUE TITLE
App won't start neither ios nor android

### ISSUE THREAD

**Issue by 0xmtn** [NativeScript/nativescript-marketplace-demo#250]
Hi,

I'm trying to get it up and running using  the command: `tns run ios` and `tns run android` 

The iOS code gets crashed with the error below:

```
error: could not read data from '/Users/mtn/Documents/projects/TRIAL/devel/apps/tns-tut/nativescript-marketplace-demo/platforms/ios/nativescriptmarketplacedemo/nativescriptmarketplacedemo-Info.plist': The file “nativescriptmarketplacedemo-Info.plist” couldn’t be opened because there is no such file.

** BUILD FAILED **


The following build commands failed:
	ProcessInfoPlistFile build/emulator/nativescriptmarketplacedemo.app/Info.plist nativescriptmarketplacedemo/nativescriptmarketplacedemo-Info.plist
(1 failure)
Command xcodebuild failed with exit code 65
```

Android gives the following:
```
Cannot run your app in the native emulator. Increase the timeout of the operation with the --timeout option or try to restart your adb server with 'adb kill-server' command. Alternatively, run the Android Virtual Device manager and increase the allocated RAM for the virtual device.
```
AVD's RAM is set to 3072.

How should I proceed?

Thanks in advance and thanks for the good work!

**Comment by tsonevn** [comment]
Hi @0xmtn,
I reviewed your problem, however was unable to reproduce this behavior.
Could you verify whether you are using latest NativeScript `2.4.2` and if not, could you upgrade to latest using the instructions here. if this does not help could you give us some more info about your environment (`node`, `CLI`, `Xcode` versions) , to build the project with `tns run <platform_name> --log trace` and to send us the full log from the Terminal.

I look forward to hearing from you

**Comment by NickIliev** [comment]
@0xmtn try to start your emulator in advance to avoid the timeout for Android.

**Comment by 0xmtn** [comment]
Hey fellas,

Somehow the problem is solved without me trying anything. I'll keep you posted in case it happens again.

Thanks for your feedback.
