### ISSUE TITLE
App crash with ios (firebase error)

### ISSUE THREAD

**Issue by dogabudak** [NativeScript/nativescript-marketplace-demo#256]
After application starts it gives an error , and application crashes. log trace gave me this error.  

> [Firebase/Core][I-COR000009] The GOOGLE_APP_ID either in the plist file 'GoogleService-Info.plist' or the one set in the customized options is invalid. If you are using the plist file, use the iOS version of bundle identifier to download the file, and do not manually edit the GOOGLE_APP_ID. You may change your app's bundle identifier to 'org.nativescript.examples'. Or you can download a new configuration file that matches your bundle identifier from https://console.firebase.google.com/ and replace the current one.

How can i fix it ?

**Comment by dogabudak** [comment]
actually a similar error happens in android too. Again some firebase problems

**Comment by NickIliev** [comment]
@dogabudak on which branch you are experiencing this? Keep in mind that the final version of this application is available on Google Play and in AppStore with enabled firebase notifications and storage. However, in the working branches the files that hold the firebase credentials are not public, so if you want to run the application locally, you should generate your **google_services.json** (for Android) and/or **GoogleService-Info.plist** (iOS)  and add those files in the respective places as shown in the instruction of [nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase).

As the marketplace is customised application for demonstration purposes I would recommend also getting familiar with more basic scenarios on how to use firebase plugin. 

Here are some step-by-step POCs for working with [RealTimeDB](https://github.com/NickIliev/NativeScript-Firebase-Realtime-DB), [Storage ](https://github.com/NickIliev/NativeScript-Firebase-Storage)and [Firebase Auth](https://github.com/NickIliev/NativeScript-Firebase-Auth)

cp -f ./ns-setup/ci/QSF/google-services.json $app/app/App_Resources/Android/
cp -f ./ns-setup/ci/QSF/GoogleService-Info.plist $app/app/App_Resources/iOS/
