### ISSUE TITLE
Where is the url/location of the JavaScript version of nativescript-marketplace-demo

### ISSUE THREAD

**Issue by mawoole** [NativeScript/nativescript-marketplace-demo#262]
Please, I need the .js and not the .ts version

**Comment by NickIliev** [comment]
Hey, @mawoole all TypeScript projects are always transpiling their *.ts files to *.js file (meaning that the TypeScript is "translated" to pure javaScript) and that said you can simply build your TS project and after the build is complete all */ts files will have generated respective */js files. 
The even easier steps is to call the TyepeScript transpiler with 
```
tsc
```
 in your project which will simply tranpile all TS files into JS.

The result (n both cases) is that you will have both **app.ts** and **app.js** both with the same code once written in TypeScript and once in JavaScript. So when working with TS you are basically working with JavaScript with all the goodies TypeScript is giving but at the end the VMs are reading the JavaScript files.

**Comment by mawoole** [comment]
Ok Thanks
