### ISSUE TITLE
Release date with 3.0 for iOS ?

### ISSUE THREAD

**Issue by kuashe** [NativeScript/nativescript-marketplace-demo#270]
I was wondering if the app with version 3.0 of the framework was going to be released anytime soon ?

**Comment by NickIliev** [comment]
@kuashe we are currently working on it and the release is expected pretty soon so stay tuned!

**Comment by kuashe** [comment]
Just downloaded version 3.X on iPhone 5c 

Nativescript is now much faster .

Animations arent laggy anymore and feels like objective c or swift performance.

Application start in just 3 seconds , it's super impressive. 

Thanks !
