### ISSUE TITLE
Marketplace item list is disappearing

### ISSUE THREAD

**Issue by PawelOwczarekFalcon** [NativeScript/nativescript-marketplace-demo#278]
I do not know how to describe this issue. Just look video https://youtu.be/yT-olB32LOg

I tested this demo app on android (galaxy alpha - android v.5.0.1), the same issue is in android emulator. After that I downloaded app from google play and it works fine.

**Comment by NickIliev** [comment]
Closing as the issue is not reproducible with the latest update
