### ISSUE TITLE
tns run ios error

### ISSUE THREAD

**Issue by FrontendOrla** [NativeScript/nativescript-marketplace-demo#279]
I'm very new to this but trying to run app on terminal and getting this warning error:
**npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support**

I've successfully run the "groceries" example app on the ios simulator so not sure what the problem is here. 

Thanks, 
Orla

**Comment by tsonevn** [comment]
Hi @FrontendOrla,
First of all, thank you for your interest in NativeScript.
I tested the project build on my side locally, however, was unable to recreate an issue, while using tns run ios command. 
Regarding that, it would help if you could provide some info about your environment(CLI, node, npm, Xcode versions) and the exact steps, which you used while building the app.
Also, you could build the app with `tns run ios --log trace` and to send us the full log from the console.

I would like to notice that the above-mentioned message is only a warning, which should not prevent you from building the app.
