### ISSUE TITLE
Error: argument `$color` of `darken($color, $amount)` must be a color

### ISSUE THREAD

**Issue by weilianglei123** [NativeScript/nativescript-marketplace-demo#283]
when i run 'tns run ios ' have issue.

Found peer node-sass
Error: argument `$color` of `darken($color, $amount)` must be a color

       Backtrace:
        node_modules/bootstrap/scss/_variables.scss:142, in function `darken`
        node_modules/bootstrap/scss/_variables.scss:142
        on line 142 of node_modules/bootstrap/scss/_variables.scss
>> $link-hover-color:          darken($link-color, 15%) !default;
   ----------------------------^

**Comment by vchimev** [comment]
https://github.com/NativeScript/theme/issues/139

**Comment by NickIliev** [comment]
Closing as the issue is no longer reproducible in this application (SASS removed in favour of CSS)
