### ISSUE TITLE
Move away from Telerik Analytics

### ISSUE THREAD

**Issue by etabakov** [NativeScript/nativescript-marketplace-demo#293]
With the retirement of Telerik Analytics - the service is no longer available. We should delete it and if we still need to track analytics data - find an alternative.

**Comment by NickIliev** [comment]
@etabakov we've just removed the Analytics with the application update (via [this PR](https://github.com/NativeScript/nativescript-marketplace-demo/pull/294)). Open to suggestion about an alternative solution (if we want to track crashes and error we might implement [Crashlytics](https://firebase.google.com/docs/crashlytics/get-started?authuser=0))
