### ISSUE TITLE
Publish latest version to App Store / PlayStore

### ISSUE THREAD

**Issue by kuashe** [NativeScript/nativescript-marketplace-demo#296]
Is it possible to get the latest version for both App Store and iOS Store ?

The current published version date from last year 😕

**Comment by NickIliev** [comment]
@kuashe the updated version is in the master branch. We have planned publishing new version in both stores pretty soon.

**Comment by vahidvdn** [comment]
+1

**Comment by kuashe** [comment]
@NickIliev Any update on this 😬 ?

**Comment by NickIliev** [comment]
@kuashe @vahidvdn  I've updated the source of the repository - stay tuned for updates in the app stores.

**Comment by kuashe** [comment]
Closing , I'll stay tune for update on the App Store.
