### ISSUE TITLE
When sidebar is open it doesnt't stop the back button navigation

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-marketplace-demo#46]

**Comment by valentinstoychev** [comment]
Click on All controls, click on SideDrawer, and when you click on the back button the app is closed. The SideDrawer should be closed instead.

Doesn't happen all the time, but quite often.

**Comment by dtopuzov** [comment]
Not valid with latest version.

**Comment by vahidvdn** [comment]
Still the issue persist.
