### ISSUE TITLE
[Android] Chart series icons do not show on the screen with animations

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-marketplace-demo#64]
Tested http://nsbuild01:8080/build/view/TestApps-Stable/job/tns-stable-build-testapps-QSF-Android/77/ on our Galaxy S4 devices.

![screen](https://cloud.githubusercontent.com/assets/12251337/11094449/893c71a2-8898-11e5-9f7b-13be63a34056.png)

**Comment by PanayotCankov** [comment]
This screen is obsolete
