### ISSUE TITLE
You can't go back from the conference example

### ISSUE THREAD

**Issue by blackxored** [NativeScript/nativescript-marketplace-demo#87]
Stuck on keyboard open and no back button.

**Comment by PanayotCankov** [comment]
Hi,

This is an issue we are aware of, there is a way to enter some text in some of the TextBoxes and hide the keyboard but that is far from user friendly. We are planing a solution such as detecting whether the keyboard is open and display the bottom-left back button over the keyboard when the keyboard is open.

Thank you for your interest in the NativeScript framework.

**Comment by PanayotCankov** [comment]
This has been redesigned now.
