### ISSUE TITLE
android.os.Build.VERSION ?

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/nativescript-marketplace-demo#89]
android.os.Build.VERSION > 18

app/examples/listview/layouts/listview-layouts.ts

Is this supposed to work? If I remove the if() block and let it run, it works but I don't think android.os.Build is going to succeed in this block. Unless I'm missing something major here about checking platform specific stuff.

**Comment by ginev** [comment]
@bradmartin this has been addressed! thanks!
