### ISSUE TITLE
Add crash reporting

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-marketplace-demo#95]
Consider making a plugin Crashlytics or a similar crash reporting tool.

**Comment by valentinstoychev** [comment]
See how we can report the JS call stack.

**Comment by valentinstoychev** [comment]
we can use Telerik analytics for this.

**Comment by hamorphis** [comment]
We can't add robust crash reporting for iOS at the current moment.

**Comment by valentinstoychev** [comment]
will we have it for Android?

**Comment by PanayotCankov** [comment]
Yes, it is enabled for Android and reports unhandled errors for iOS.

**Comment by hypery2k** [comment]
I've create a fabric plugin for [nativescript](https://github.com/hypery2k/nativescript-fabric). It supports basic Crashlytics usage and has also iOS support in the develop version. 

I plan to release version 0.1.0 with stable API in january with support for iOS and Android.
If anyone would like to support the development, feel free to sent PR and/or donations ;)

**Comment by hypery2k** [comment]
just to note: I've published a new version of my [plugin](https://www.npmjs.com/package/nativescript-fabric). It now supports Crashlytics on iOS and Android with TypeScript support

**Comment by PieterAelse** [comment]
@hypery2k Is it also possible to use with NS + plain JS? (we're not using TS or Angular)
